In [1]:
import math

from numpy import matrix

1+1

2

In [2]:
print('Hello world')

Hello world


In [3]:
matrix=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
[[i+1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [7]:
# 导入Numpy
import numpy as np
array1=np.array([10,100,1000]) # 列表构建一个一维数组
array2=np.array([[1.,2.,3.],[4.,5.,6.]])# 使用嵌套构建一个二维数组
array1.dtype

dtype('int32')

In [8]:
float(array1[0])

10.0

In [9]:
array2+1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [10]:
array2*array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [13]:
import math 
np.array([[math.sqrt(i) for i in row] for row in array2])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [14]:
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [17]:
array2.sum(axis=0)# 返回维数组 axis=0 表示以行为轴，1 是表示以列为轴

array([5., 7., 9.])

In [18]:
array2.sum()# 表示把数组内的所有数组加起来

21.0

In [19]:
array1[2]

1000

In [20]:
array2[0,0]

1.0

In [21]:
array2[:,1:]

array([[2., 3.],
       [5., 6.]])

In [22]:
array2[:,1]#返回一维数组

array([2., 5.])

In [24]:
array2[1,:2]

array([4., 5.])

In [26]:
np.arange(2*5).reshape(2,5)# array 代表array range (数组范围)  通过arange 和reshape 可以快速生成指定纬度的数组

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.random.randn(2,3) # 蒙特卡罗模拟，生成服从正态分布的伪随机数数组

array([[ 1.09173246, -0.5967623 ,  0.23742912],
       [-3.72345251, -0.01103002, -1.05698052]])

In [29]:
import pandas as pd
pd.read_excel('E:/pythonProject3/pythonProject3/jupyter/course_participants.xlsx')

user_id   name  age  country   score continent
0     1001   Mark   55    Italy 4.50000    Europe
1     1000   John   33      USA 6.70000   America
2     1002    Tim   41      USA 3.90000   America
3     1003  Jenny   12  Germany 9.00000    Europe

In [31]:
data=[['Mark',55,'Italy',4.5,'Europe'],
        ['John',33,'USA',6.7,'Europe']
      ]
df=pd.DataFrame(data=data,columns=['Name','Age','Country','Score','Continent'],index=[1001,1002])
df

Name  Age Country   Score Continent
1001  Mark   55   Italy 4.50000    Europe
1002  John   33     USA 6.70000    Europe

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 1001 to 1002
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Name       2 non-null      object 
 1   Age        2 non-null      int64  
 2   Country    2 non-null      object 
 3   Score      2 non-null      float64
 4   Continent  2 non-null      object 
dtypes: float64(1), int64(1), object(3)
memory usage: 96.0+ bytes


In [33]:
df.index

Int64Index([1001, 1002], dtype='int64')

In [35]:
df.index.name='Use_id'
df

Name  Age Country   Score Continent
Use_id                                     
1001    Mark   55   Italy 4.50000    Europe
1002    John   33     USA 6.70000    Europe

In [36]:
df.reset_index()# 将索引还原为普通列，同时用默认索引替换当前索引
# 最终结果和刚开始一样
df

Name  Age Country   Score Continent
Use_id                                     
1001    Mark   55   Italy 4.50000    Europe
1002    John   33     USA 6.70000    Europe

In [37]:
df.reset_index().set_index('Name')# index 将User_id 还原成普通列 set_index 将name 列设置为索引
#以上用的这形式为链式方法调用

Use_id  Age Country   Score Continent
Name                                       
Mark    1001   55   Italy 4.50000    Europe
John    1002   33     USA 6.70000    Europe

In [40]:
df.reset_index().set_index('Use_id')

Name  Age Country   Score Continent
Use_id                                     
1001    Mark   55   Italy 4.50000    Europe
1002    John   33     USA 6.70000    Europe

In [41]:
df.reindex([999,1001,1002])# 用reindex方法更换索引

Name      Age Country   Score Continent
Use_id                                         
999      NaN      NaN     NaN     NaN       NaN
1001    Mark 55.00000   Italy 4.50000    Europe
1002    John 33.00000     USA 6.70000    Europe

In [42]:
df.sort_index()# 安装索引进行排序

Name  Age Country   Score Continent
Use_id                                     
1001    Mark   55   Italy 4.50000    Europe
1002    John   33     USA 6.70000    Europe

In [45]:
df.sort_values(['Continent','Age'])

Name  Age Country   Score Continent
Use_id                                     
1002    John   33     USA 6.70000    Europe
1001    Mark   55   Italy 4.50000    Europe